services:
  - type: web
    name: social-media-integration-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    autoDeploy: true 