services:
  - type: web
    name: social-media-integration-frontend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NITRO_HOST
        value: 0.0.0.0
      - key: NITRO_PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true 